### ISSUE TITLE
Plz send me some feedback on the code.

### ISSUE THREAD

**Issue by herobrine1010** [Vagrant-Zero/python-crawl#1]
Plz send me some feedback on the code. That's important to me 🤣

**Comment by Vagrant-Zero** [comment]
Ok, thanks for your invitation!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Vagrant-Zero/python-crawl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月11日(星期二) 下午3:34
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Vagrant-Zero/python-crawl] Plz send me some feedback on the code. (#1)





 
Plz send me some feedback on the code. That's important to me 🤣
